image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

before_script:
  - docker info
  - docker compose version

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker compose build
  artifacts:
    paths:
      - .

test:
  stage: test
  script:
    - docker compose up -d
    - sleep 10  # Give services time to start
    - curl -f http://localhost:8765 || exit 1  # Basic health check
    - docker compose down
  dependencies:
    - build

deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
  only:
    - main
  when: manual 