version: '3'
services:
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8765:80"
    depends_on:
      - timeserver1
      - timeserver2
      - timeserver3

  timeserver1:
    build: 
      context: .
      dockerfile: Dockerfile.node
    environment:
      - SERVER_ID=1

  timeserver2:
    build: 
      context: .
      dockerfile: Dockerfile.node
    environment:
      - SERVER_ID=2

  timeserver3:
    build: 
      context: .
      dockerfile: Dockerfile.node
    environment:
      - SERVER_ID=3 